<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLg9JCE4\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLg9JCE4/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLg9JCE4.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLg9JCE4\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLg9JCE4\App_KernelDevDebugContainer([
    'container.build_hash' => 'Lg9JCE4',
    'container.build_id' => '67378a2a',
    'container.build_time' => 1595928851,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLg9JCE4');
